### PR TITLE
Anastasia_Kichaeva_Hw1_Task2

### PR DESCRIPTION
**Pull request by AnastasiaKichaeva**

### CODE REVIEW

**Review by GennadiyPitsukha — DISMISSED** [review]

**Review by VladimirPetranovski — APPROVED** [review]
LGFM

**Review by tatianamih — APPROVED** [review]

**Review by tatianamih — APPROVED** [review]
lgfm

**Comment by lamaconda** [comment]
LGFM

**Review by lamaconda — APPROVED** [review]
lgfm

**Review by lamaconda — APPROVED** [review]
lgfm

**Review by lamaconda — APPROVED** [review]
lgfm

**Review by lamaconda — APPROVED** [review]

**Review by GennadiyPitsukha — APPROVED** [review]
lgfm

**Pull request merged**
