### PR TITLE
Nikita maistrenko hw1 task2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by AnastasiaKichaeva — APPROVED** [review]

**Review by rus-sto — APPROVED** [review]
lgfm (but not sure that to each string new public void is needed)

**Comment by rus-sto** [comment]
lgfm

**Comment by kdmitry123** [comment]
lgfm

**Review by kdmitry123 — APPROVED** [review]
lgfm

**Comment by ghost** [comment]
> lgfm (but not sure that to each string new public void is needed)

May be) However, if i need update my code for smth new, i will be use my methods. And it solution better for updating.

**Pull request merged**
