### PR TITLE
Create first homework

### PR DESCRIPTION
**Pull request by javaGuruBY**

### CODE REVIEW

**Review by asraysun — APPROVED** [review]
lgfm

**Comment by GennadiyPitsukha** [comment]
Lgfm

**Comment by GennadiyPitsukha** [comment]
Lgfm

**Review by GennadiyPitsukha — APPROVED** [review]
lgfm

**Review by tatianamih — APPROVED** [review]
Looks good for me

**Review by VladimirPetranovski — APPROVED** [review]
Lgfm

**Pull request merged**
